name: Smart CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  react-frontend:
    name: React Frontend Build & Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build React App
        working-directory: frontend
        run: npm run build

      - name: Run SonarCloud Scan
        working-directory: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=yash-jawoor1_ci-cd-runcloud-demo \
            -Dsonar.organization=yashrajsingh \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.sources=src \
            -Dsonar.exclusions=**/node_modules/**,**/*.test.js

  php-backend:
    name: PHP Backend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Lint PHP files
        run: find backend -name "*.php" -exec php -l {} \;

  html-validator:
    name: HTML Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate HTML files
        run: htmlhint "html/**/*.html" || true

